name: orb
version: "5.0.0"
license: "GPL-3.0-or-later"
date: 2025-01-22
description: |
    Methods to enumerate orbits

authors:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske

maintainers:
    - name: Juergen Mueller
      url: http://www.math.rwth-aachen.de/~Juergen.Mueller
    - name: Felix Noeske
      url: http://www.math.rwth-aachen.de/~Felix.Noeske
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.12"

suggested-pkgs:
    - name: "IO"
      version: ">= 3.3"
      url: "https://gap-packages.github.io/io"

www: https://gap-packages.github.io/orb
readme: README.md
packageinfo: https://gap-packages.github.io/orb/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/orb/releases/download/v5.0.0/orb-5.0.0.tar.gz

abstract: |
    The <span class="pkgname">orb</span> package is about enumerating orbits in various ways.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Orbit huge, OrbitBySuborbit, hash tables, searching in groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>MNNH25</span>]   <b class='BibAuthor'>Mueller, J., Neunhöffer, M., Noeske, F. and Horn, M.</b>,
     <i class='BibTitle'>orb, Methods to enumerate orbits,
             Version 5.0.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/orb">https://gap-packages.github.io/orb</a></span>.
    </p>
    

bibtex: |
    @misc{ orb,
      author =           {Mueller,  J. and Neunh{\"o}ffer, M. and Noeske, F. and
                          Horn, M.},
      title =            {{orb}, {Methods to enumerate orbits}, {V}ersion 5.0.0},
      month =            {Jan},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href             {https://gap-packages.github.io/orb}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{orb}}},
      keywords =         {Orbit huge; OrbitBySuborbit; hash tables; searching in
                          groups},
      printedkey =       {MNNH25}
    }

